<?php

namespace App\Repository;

/**
 * AdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Adresses04Repository extends \Doctrine\ORM\EntityRepository
{
}
