<?php

namespace App\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Clients02Repository extends \Doctrine\ORM\EntityRepository
{
}
