<?php

namespace App\Repository;

/**
 * CompagniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagniesRepository extends \Doctrine\ORM\EntityRepository
{
}
