<?php

namespace App\Repository;

/**
 * employee_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employee_type01Repository extends \Doctrine\ORM\EntityRepository
{
}
