<?php

namespace App\Repository;

/**
 * EmployeesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Employees03Repository extends \Doctrine\ORM\EntityRepository
{
}
