<?php

namespace App\Repository;

/**
 * InvoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Invoices03Repository extends \Doctrine\ORM\EntityRepository
{
}
