<?php

namespace App\Repository;

/**
 * meetingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class meeting04Repository extends \Doctrine\ORM\EntityRepository
{
}
