<?php

namespace App\Repository;

/**
 * MessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Messages04Repository extends \Doctrine\ORM\EntityRepository
{
}
