<?php

namespace App\Repository;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Products03Repository extends \Doctrine\ORM\EntityRepository
{
}
